[package]
name = "oxy-fi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
handlebars = "4.3.7"
reqwest = "0.11.18"
tokio = "1.28.1"
